// <auto-generated />
namespace FurnitureProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ImagePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImagePath));
        
        string IMigrationMetadata.Id
        {
            get { return "201508260930262_ImagePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
